### ISSUE TITLE
Feature 1: User can search movies and tv shows by name.

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/ajax-project#1]
## ⚙️ Users can search movies and tv shows by name

> ##### What capability will users have when this feature is merged?
The user's will get to this page when the users press on the search icon.

## 📐 Functionality

> The user is able to type the movie or tv show title from the searchbar 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

https://github.com/Jumanah-A/ajax-project/issues/1

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create HTML, CSS, and JavaScript files.
- [x] Build HTML skeleton.
- [x] create data-views div with value of:
- [x] -- search view
- [x] add image as the background for the entire homepage/ search page
- [x] create a search bar using the text area
- [x] create a icon, button for the search magnifying class icon 
- [x] --style the search box 
- [x] --using dark theme and border radius
- [x] --add placeholder 
- [x] add css mobile responsive rule sets 
- [x] create a grid with rows and column 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
