### ISSUE TITLE
Feature: User can view movie information

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view movie information.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After typing the title of the movie or tv show the user can then view the movie poster, title, year, plot, and IMDb rating of the movie.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create another div with the data-view attribute with the value "movie-view"
- [x] create a dummy movie entry 
- [x] style that dummy movie entry to look like the wireframe
- [x] comment out the dummy entry
- [x] style that page to have the watchlist title logo on the top left of the page and my watchlist title logo to be right next to it (in the header element in the body.
- [x] In the main.js file : -->
- [x] query the DOM for the search icon anchor element
- [x] add an event listener to that dom element 
- [x] create a function that switches between the two views of the search and the movie view
- [x] create a function to handle the click of the search icon 
- [x] -- in that function call the switch view function 
- [x] create another function that grabs the information from the API using the xhr object 
- [x] after grabbing the info
- [x] display the info on the page 
- [x] create a DOM tree to display the information on the page and update it to look like the dummy code
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
