### ISSUE TITLE
Feature: User can add movie to watchlist

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add movie to watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
After the user views the movie they can add it to their watchlist by pressing the add to watchlist button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a "My watchlist" button to the header 
- [x] add an event listener to the "my watchlist" button
- [x] create a data-view div called "my-watchlist"
- [x] style a dummy my watchlist page
- [x] mimic that style in the dom tree 
- [x] add a watchlist button to the dom tree 
- [x] add an event listener to the button 
- [x] create a data model for the watchlist movies 
- [x] save data model in the local storage
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
