### ISSUE TITLE
Feature: User can rate a movie or a tv show

### ISSUE THREAD

**Issue by Jumanah-A** [Jumanah-A/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can rate the movies or tv shows by clicking on the rate button which shows the rating stars

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a dummy rating HTML code
- [x] write the css code for the dummy stars
- [x] create a div for the the stars
- [x] create a rate button 
- [x] once the button is pressed show the rating div 
- [x] to calculate the rating values
- [x]  iterate over the children of the div 
- [x] update the rating n the data model whenever the user presses the rate button 
- [x] update each objects rating value in the data model
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
